### ISSUE TITLE
O mapa com Zoom incorreto

### ISSUE THREAD

**Issue by nexusbr-geoengenharia** [geopixelsjc/WebThematicMaps_server#2]
O mapa com os municípios de São Paulo quando realizo o mapa temático vem com zoom afastado. Antes vinha com zoom no Estado de São Paulo.

**Comment by nexusbr-geoengenharia** [comment]
David, ao fechar esta issue, favor descrever o que foi feito para corrigir e o commit gerado com o código que foi modificado para isso ser corrigido. Favor colocar o número do commit na issue fechada.

**Comment by nexusbr-geoengenharia** [comment]
Mapa ficou minúsculo agora e não aparece mais o mapa temático.

**Comment by dvdpansardis** [comment]
O problema foi corrigido com a re-importação do shape no servidor que estava com a tabela duplicada.

**Comment by geopixelsjc** [comment]
Qual o nome da tabela? Como foi realizada esta re-importação. Não consegui entender o que foi realizado.
